export const RouteName = {
  Home: 'global',
  Product: 'product-slug',
  CollectionByCategory: 'product-category-slug',
  Cart: 'cart',
  Recipes: 'recipes',
  RecipesDetails: 'recipes-id',
  Blog: 'blog',
  BlogDetails: 'blog-id',
  Reviews: 'reviews',
  Quality: 'quality',
  PaymentDelivery: 'payment-delivery',
  About: 'about',
  Favorite: 'favorite',
  Contacts: 'contacts',
  Checkout: 'checkout',
  CheckoutReport: 'checkout-report',
  PersonalAccount: 'personal-account',
  Order: 'order-id',
  Search: 'search',
  PrivacyPolicy: 'privacy-policy',
  PasswordRecovery: 'password-recovery',
  PageNotFound: 'PageNotFound',
  GenerateSitemap: 'generate-sitemap'
}